---
- hosts: db
  become: yes
  vars_files:
    - vars/drupal.yml
    - vars/wordpress.yml
    - vars/laravel.yml
  roles:
    - mysql
    - drupal-db
    - wordpress-db
    - laravel-db

- hosts: web
  become: yes
  vars_files:
    - vars/drupal.yml
    - vars/wordpress.yml
    - vars/laravel.yml
    - vars/static-sites.yml
  roles:
    - devtools
    - nginx
    - php-fpm
    - xdebug
    - node
    - sculpin
    - drupal-web
    - wordpress-web
    - laravel-web
    - static-sites

- hosts: ci
  become: yes
  roles:
    - jenkins
